name = "StructureTensor"
uuid = "e8f2c1a0-5b3d-4e7f-9a1b-2c3d4e5f6a7b"
version = "0.1.0"
authors = ["Andrew Keenlyside"]

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NIfTI = "a3a9e032-41b5-5fc4-967a-a6b7a19844d3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TiffImages = "731e570b-9d59-4bfa-96dc-6df516fadf69"

[extensions]
CUDAExt = "CUDA"

[compat]
CUDA = "5"
ImageFiltering = "0.7"
NIfTI = "0.6.1"
StaticArrays = "1"
TiffImages = "0.11.6"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
